name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Build and Push to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug Repository URI
        run: echo $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Load secrets from AWS Secrets Manager and save to app.env
        run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Debug app.env content after AWS Secrets Manager
        run: cat app.env

      - name: Load secrets from GitHub Secrets to app.env
        run: |
          echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
          echo "TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }}" >> app.env
          echo "ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }}" >> app.env

      - name: Debug app.env content after GitHub Secrets
        run: cat app.env

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg DB_SOURCE="${DB_SOURCE}" \
            --build-arg SERVER_ADDRESS="${SERVER_ADDRESS}" \
            --build-arg TOKEN_SYMMETRIC_KEY="${TOKEN_SYMMETRIC_KEY}" \
            --build-arg ACCESS_TOKEN_DURATION="${ACCESS_TOKEN_DURATION}" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
